### ISSUE TITLE
"typ" header parameter value is optional according to RFC7519 but is required in this library

### ISSUE THREAD

**Issue by JonNode28** [panva/oauth4webapi#118]
### What happened?

AWS Cognito access tokens don't have the "typ" header parameter value which seems to be compliant with the [RFC7519](https://datatracker.ietf.org/doc/html/rfc7519#page-11) spec but this library errors if it is not present. From the validateJwtAccessToken() function we have the following logic:

```javascript
function checkJwtType(expected, result) {
    if (typeof result.header.typ !== 'string' || normalizeTyp(result.header.typ) !== expected) {
        throw new OPE('unexpected JWT "typ" header parameter value');
    }
    return result;
}
```

### Version

v2.10.3

### Runtime

Node.js

### Runtime Details

v20.11.1

### Code to reproduce

```js
{}
```

### Required

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/oauth4webapi/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
Absolutely same reasoning as in https://github.com/panva/oauth4webapi/issues/117#issuecomment-2027456482
