### ISSUE TITLE
Cross Origin Request Blocked: User Agent on discovery fetch

### ISSUE THREAD

**Issue by Leon0402** [panva/oauth4webapi#13]
### What happened?

I'm getting CORS errors with `discoveryRequest` and GitLab. Some minimal reproducable code:

```
const issuer = new URL("https://gitlab.com/.well-known/openid-configuration");
const as = await oauth.discoveryRequest(issuer);
```

I'm not a web developer, but I'm quite sure it is related to the library overriding the user-agent in `prepareHeaders`. Some minimal reproducable code without using the library: 

```
const issuer = new URL("https://gitlab.com/.well-known/openid-configuration");

const headers = new Headers();
headers.set("user-agent", "oauth4webapi/v1.0.3"); // Works without this line
headers.set("accept", "application/json");

fetch(issuer.href, { headers, method: "GET", redirect: "manual" })
  .then((response) => response.json())
  .then((data) => console.log(data));
```

Should the user-agent really be the library? Usually it is the browser, isn't it?

### Version

v1.0.3

### Runtime

Browser

### Runtime Details

Linux, Firefox & Chrome

### Code to reproduce

```js
const issuer = new URL("https://gitlab.com/.well-known/openid-configuration");
const as = await oauth.discoveryRequest(issuer);
```

### Required

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/oauth4webapi/blob/main/CODE_OF_CONDUCT.md)

**Comment by Leon0402** [comment]
I actually checked again and `discoveryRequest` is neither working in Firefox nor Chrome. But my second code with fetch content actually works in Chrome. So while `user-agent` is (one of) the reasons it is not working in Firefox, there must be some other reason for chrome.

**Comment by panva** [comment]
> I actually checked again and discoveryRequest is neither working in Firefox nor Chrome.

You need to use it right first, the `Issuer Identifier` URL instance you pass in must be `new URL('https://gitlab.com')`, not including the well known components.

See CORS made discovery from Chrome.

<img width="1182" alt="image" src="https://user-images.githubusercontent.com/241506/172917789-266b7f76-3abb-40e0-98de-8aaca484a820.png">

Please reach out to gitlab support with this issue of theirs first. There's something awry with their CORS configuration when non-default user-agent is provided. This discovery mechanism works against other providers. Happy to look into it again if it turns out to be a non-gitlab specific issue.

Also keep in mind, as a workaround, you can discover / obtain the metadata object any way that works for you with gitlab.

**Comment by panva** [comment]
You can also pass custom headers to all network utilizing functions. So you may just pass a Headers instance with user-agent being the navigator.userAgent which would be otherwise used by default if not defined by the library.

**Comment by panva** [comment]
https://github.com/panva/oauth4webapi/releases/tag/v1.0.4

**Comment by Leon0402** [comment]
> You need to use it right first, the `Issuer Identifier` URL instance you pass in must be `new URL('https://gitlab.com')`, not including the well known components.

Oh yes, you're right!


I think the reason that it's not working in firefox, but in chromium, might be that settings the user agent is not possible in chromium? At least I read this in various sources and found and found an open bug for it:

https://bugs.chromium.org/p/chromium/issues/detail?id=571722

Additionally when looking at my network tab, the user agent is not set to `oauth4webapi/v1.0.3`, but to the default value. 

The SO answer https://stackoverflow.com/a/42815264/10764260 provided that link and also said that a custom user-agent used to be not allowed. So that might be a possible explanation why GitLab (and others) forbid it? 

Again, I have very little experience with web stuff. So I'm just guessing here.

**Comment by Leon0402** [comment]
> https://github.com/panva/oauth4webapi/releases/tag/v1.0.4

I can confirm that your commit fixed the issue in firefox and chromium. Thanks for quick help!
