### ISSUE TITLE
`protectedResourceRequest` with dpop is hardcoded as GET request

### ISSUE THREAD

**Issue by tom-sherman** [panva/oauth4webapi#132]
### What happened?

I attempted to make a POST request using previously fetched dpop info but the server failed because the `htm` claim in the dpop jwt is always GET.

### Version

v2.11.1

### Runtime

Node.js

### Runtime Details

v20.9.0

### Code to reproduce

```js
await protectedResourceRequest(
  session.user.accessToken,
  "POST", // I want to do a POST request
  new URL(request.url),
  request.headers,
  request.body,
  {
    DPoP: {
      privateKey: privateDpopKey,
      publicKey: publicDpopKey,
      nonce: session.user.dpopNonce,
    },
  },
);
```

### Required

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/oauth4webapi/blob/main/CODE_OF_CONDUCT.md)

**Comment by tom-sherman** [comment]
Patching this from a hardcoded string to be the `method` param that's passed into the function seems to work.

https://github.com/panva/oauth4webapi/blob/eddc66f75375674947d57ea57498e2d28a900d06/src/index.ts#L2136

**Comment by panva** [comment]
Oh wow. Indeed a bug! Will fix

**Comment by panva** [comment]
https://github.com/panva/oauth4webapi/releases/tag/v2.12.1

**Comment by panva** [comment]
Thank you for the report.
