### ISSUE TITLE
The base64 result of clientSecret encoding is abnormal.

### ISSUE THREAD

**Issue by ck76** [panva/oauth4webapi#148]
### What happened?

This issue seems different from https://github.com/panva/oauth4webapi/issues/69.
I found that when using basic auth, the base64 encoding in the Authorization header processed by oauth4webapi cannot encode and decode '-', '_', etc.
Here is my code.
```typescript
 let client_secret = '0jQKm_heHj4Ba7-IPXk1bZbnKvG5SV5BCjtXpYjVok8BUsOveM0MEtgeS0hPgeftSu_jYlYysILt7nQHBTIzPg';
const clientSecretBasic = oauth.ClientSecretBasic(client_secret);
const request =  oauth.authorizationCodeGrantRequest(
        oauth_authorization_server,
        { client_id },
        clientSecretPost,
        params,
        redirect_uri,
        code_verifier,
    )
```
This is the base64 encoded string after oauth4webapi processing: MTM0NDg1MTk2OTY2NTc6MGpRS20lNUZoZUhqNEJhNyUyRElQWGsxYlpibkt2RzVTVjVCQ2p0WHBZalZvazhCVXNPdmVNME1FdGdlUzBoUGdlZnRTdSU1RmpZbFl5c0lMdDduUUhCVEl6UGc=

Decoded string:
13448519696657:0jQKm%5FheHj4Ba7%2DIPXk1bZbnKvG5SV5BCjtXpYjVok8BUsOveM0MEtgeS0hPgeftSu%5FjYlYysILt7nQHBTIzPg

The string that should be output after decoding:
13448519696657:0jQKm_heHj4Ba7-IPXk1bZbnKvG5SV5BCjtXpYjVok8BUsOveM0MEtgeS0hPgeftSu_jYlYysILt7nQHBTIzPg
![QQ_1730088353117](https://github.com/user-attachments/assets/ecec6b68-c34b-4e4a-a51c-1ddccca2e783)

### Version

3.1.2

### Runtime

Browser

### Runtime Details

macos

### Code to reproduce

```js
This issue can be reproduced by using a client Secret with "-" or "_".

let client_secret = '0jQKm_heHj4Ba7-IPXk1bZbnKvG5SV5BCjtXpYjVok8BUsOveM0MEtgeS0hPgeftSu_jYlYysILt7nQHBTIzPg';
const clientSecretBasic = oauth.ClientSecretBasic(client_secret);
const request =  oauth.authorizationCodeGrantRequest(
        oauth_authorization_server,
        { client_id },
        clientSecretPost,
        params,
        redirect_uri,
        code_verifier,
    )
```

### Required

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/oauth4webapi/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
This is as per https://www.rfc-editor.org/rfc/rfc6749.html#section-2.3.1 

the client id and client secret tokens are encoded as per appendix B before being used as the basic auth username and password.

**Comment by panva** [comment]
If your server provider doesn't follow the specification use client secret post instead or implement your own client auth following the right interface.
