### ISSUE TITLE
ReferenceError: crypto is not defined when running on Node.js v18

### ISSUE THREAD

**Issue by kuoruan** [panva/oauth4webapi#149]
### What happened?

```
ReferenceError: crypto is not defined
    at randomBytes (file:///xxx/node_modules/.pnpm/oauth4webapi@3.1.2/node_modules/oauth4webapi/build/index.js:270:17)
```

I find an issue at #8 
If this package requires Node.js 19 and later. why there is no `engines` set in `package.json`

### Version

v3.1.2

### Runtime

Node.js

### Runtime Details

Node.js v18.20.2

### Code to reproduce

```js
// test.mjs
import * as oauth from "oauth4webapi";

console.log(oauth.generateRandomState());
```

### Required

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/oauth4webapi/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
Hello @kuoruan 

> why there is no engines set in package.json

because it is historically ignored by most tooling and users and therefore doesn't do much, also doesn't have a defined meaning for a universal js module.

**Comment by kuoruan** [comment]
I'm using this package as a dependency of my package.
So is it means my user must update to Node.js 19 or set the `NODE_OPTIONS` environment variables? 😢
Why not provide different entries for browser and node.

```json
{
  "type": "module",
  "main": "./entry.node.cjs",
  "module": "./entry.node.js",
  "browser": "./entry.browser.js",
  "exports": {
    "require": "./entry.node.cjs",
    "import": "./entry.node.js",
    "script": "./entry.browser.js"
  }
}
```

**Comment by panva** [comment]
Asking for an up to date version of Node.js is not that hard pill to swallow if it means not having to deal with double the build process and double the install size.
