### ISSUE TITLE
Add support for non-standard google identity DeviceAuthorizationResponse verification_url

### ISSUE THREAD

**Issue by rgl** [panva/oauth4webapi#154]
### What happened?

Unfortunately the google identity DeviceAuthorizationResponse responds with a non-standard response:

```json
{
  device_code: "AH...9Q",
  user_code: "NCL-...-ZQK",
  expires_in: 1800,
  interval: 5,
  verification_url: "https://www.google.com/device"
}
```

As you can see, it returns `verification_url` instead of `verification_uri` (https://datatracker.ietf.org/doc/html/rfc8628#section-3.2).

Can this library add support for that quirk (e.g. add support for `verification_uri` and `verification_url`)?

There is a google issue tracking this problem since 2020 at https://issuetracker.google.com/issues/151238144... but it seems no effort was made to fix it, hence, it needs a workaround?

### Version

3.1.4

### Runtime

Deno

### Runtime Details

2.1.4

### Code to reproduce

```js
// NB this is was copied from https://github.com/panva/oauth4webapi/blob/main/examples/device_authorization_grant.ts with little changes to use google identity details.

import * as oauth from "jsr:@panva/oauth4webapi";

// Prerequisites
let issuer!: URL // Authorization server's Issuer Identifier URL
let algorithm!:
  | 'oauth2' /* For .well-known/oauth-authorization-server discovery */
  | 'oidc' /* For .well-known/openid-configuration discovery */
  | undefined /* Defaults to 'oidc' */
let client_id!: string
// End of prerequisites

// see https://developers.google.com/identity/openid-connect/openid-connect#discovery
issuer = new URL("https://accounts.google.com");
algorithm = 'oidc';

// see https://console.cloud.google.com/apis/credentials?project=example-444918
client_id = "55....apps.googleusercontent.com";
const client_secret = "GO...MR";

const as = await oauth
  .discoveryRequest(issuer, { algorithm })
  .then((response) => oauth.processDiscoveryResponse(issuer, response))

const client: oauth.Client = { client_id }
const clientAuth = oauth.None()
// const clientAuth = oauth.ClientSecretPost(client_secret);

let device_code: string
let interval: number
let verification_uri: string
let user_code: string
let verification_uri_complete: string | undefined

// Device Authorization Request & Response
{
  const parameters = new URLSearchParams()
//   parameters.set('scope', 'openid https://www.googleapis.com/auth/photoslibrary.readonly')
  parameters.set('scope', 'openid')

  const response = await oauth.deviceAuthorizationRequest(as, client, clientAuth, parameters)

  const result = await oauth.processDeviceAuthorizationResponse(as, client, response)

  console.log('Device Authorization Response', result)
  ;({ device_code, verification_uri, verification_uri_complete, user_code, interval = 5 } = result)
}
```

### Required

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/oauth4webapi/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
If they include non-standard response parameters you can still access them on the response object. It just won't be typed.

**Comment by rgl** [comment]
Indeed, I've worked around this with this ugly implementation:

```javascript
  const originalResponseJson = response.json;

  response.json = async () => {
    const j = await originalResponseJson.call(response);
    j.verification_uri = j.verification_url;
    return j;
  };
```

But it turns out, I have to give up upon the google device authorization grant, as it cannot really access the google photos scopes (my goal is to use the google photos api), so I had to abandon this route and I'm trying to use https://github.com/panva/oauth4webapi/blob/main/examples/oidc.ts instead.

So maybe this issue can be closed? As even implementing this correctly, only give us a [severely limited access to google apis scopes](https://developers.google.com/identity/protocols/oauth2/limited-input-device#allowedscopes).

**Comment by panva** [comment]
No, that's not what i meant.

```
const result = await oauth.processDeviceAuthorizationResponse(as, client, response)
console.log(result) <- it has whatever the JSON response had.
```

**Comment by rgl** [comment]
That will not work, and I'm now seeing that I did not include the error description at all... sorry about that! Without the `verification_uri` property the [oauth.processDeviceAuthorizationResponse call fails at](https://github.com/panva/oauth4webapi/blob/d93937fa2d94343899283d7a8703803c7300ed96/src/index.ts#L5520-L5525):

```javascript
assertString(
    json.verification_uri,
    '"response" body "verification_uri" property',
    INVALID_RESPONSE,
    { body: json },
  )
```

**Comment by panva** [comment]
Ah right, because it's required. Yeah, no workaround other than consuming the `Response` instance `.json()`
