### ISSUE TITLE
Auth code + PKCE without nonce check fails with an empty string for nonce in JWT

### ISSUE THREAD

**Issue by Mikk36** [panva/oauth4webapi#61]
### What happened?

When not including nonce as a check for oauth2 auth code + pkce, Hydra returns a JWT with an empty nonce field in it, but oauth4webapi seems to assume that it has to not be present at all.

![image](https://user-images.githubusercontent.com/5886412/231892467-42a03da5-133f-470e-8d64-0d5ac3641dc6.png)

https://github.com/panva/oauth4webapi/blob/bb2d34df108744be8f265ab6ed503f5d5fa0e893/src/index.ts#L2474

### Version

v2.2.1

### Runtime

Node.js

### Runtime Details

Node v16.15.0

### Code to reproduce

```js
No specific code available, tried to auth using @auth/core + @auth/sveltekit
```

### Required

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/oauth4webapi/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
Hydra is at fault. The claim is to be missing, not have an empty value.

**Comment by Mikk36** [comment]
Indeed, it was an issue with using a slightly older Hydra (1.10.1). Latest v1 (1.11.10) already has it fixed.
