### ISSUE TITLE
Allow custom discovery location?

### ISSUE THREAD

**Issue by MFinn87** [panva/oauth4webapi#63]
### What happened?

First of all, really awesome work making `oauth4webapi` and `node-openid-client`.

I'm not sure whether to label this a feature request or bug.

I'm running into an issue when sending a discovery request to the url:
`https://developer.api.intuit.com/.well-known/openid_sandbox_configuration`

You'll notice that `oauth4webapi` is appending its own `...well-known...` url portion, so it appears in duplicate:

![1B7F7D97-2497-4094-9DBC-7E99101FA4A3](https://user-images.githubusercontent.com/59815217/233270897-1f988fdb-9010-4b1d-829d-af51876084ec.jpeg)

It looks like you may have solved this in `node-openid-client` in this commit: https://github.com/panva/node-openid-client/commit/0c8a8f242effe2e444db36271de68b4b71ea8489

I realize that is a different repo, but these projects do solve a lot of the same problems and I was wondering if you'd be willing to apply the same/similar fix to this repo?

Thanks,
Mike

### Version

v2.2.1

### Runtime

Deno

### Runtime Details

deno:v1.32.4

### Code to reproduce

```js
import { discoveryRequest } from 'https://deno.land/x/oauth4webapi@v2.2.1/mod.ts'


const url = new URL('https://developer.api.intuit.com/.well-known/openid_sandbox_configuration')

const response = await discoveryRequest(url)

console.log(response)
```
```


### Required

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/oauth4webapi/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
You should just perform your own fetch request to obtain a Response and pass that to `processDiscoveryResponse` if you want to work with arbitrary discovery URLs.

**Comment by MFinn87** [comment]
Can do. Thank you.
